# 给你的机器人指令取个名字
name: Merge AdGuard Rules

# 触发指令的条件
on:
  # 1. 允许你手动在 Actions 页面点击按钮来运行
  workflow_dispatch:
  
  # 2. 定时触发：这里设置为每天凌晨2点 (UTC时间) 自动运行一次
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    # 运行环境，使用最新的Ubuntu系统
    runs-on: ubuntu-latest
    
    # 【修复】就是在这里添加了权限设置
    permissions:
      contents: write

    steps:
      # 第一步：固定写法，让机器人能访问你的仓库文件
      - name: Checkout
        uses: actions/checkout@v4

      # 第二步：下载所有的规则文件，并合并到一个临时文件里
      - name: Download and Merge
        run: |
          # 下面是你提供的上游规则列表
          echo "开始下载规则..."
          curl -sL "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt" >> temp_list.txt
          curl -sL "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt" >> temp_list.txt
          curl -sL "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt" >> temp_list.txt
          curl -sL "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt" >> temp_list.txt
          curl -sL "https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/adblock.txt" >> temp_list.txt
          curl -sL "https://raw.githubusercontent.com/hululu1068/AdGuard-Rule/main/rule/all.txt" >> temp_list.txt
          curl -sL "https://raw.githubusercontent.com/xndeye/adblock_list/refs/heads/release/easylist.txt" >> temp_list.txt
          curl -sL "https://lingeringsound.github.io/adblock_auto/Rules/adblock_auto.txt" >> temp_list.txt
          curl -sL "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt" >> temp_list.txt
          echo "规则下载完成！"

      # 第三步：处理合并后的文件：去重、排序、移除无效行
      - name: Process Rules
        run: |
          echo "开始处理规则..."
          # 移除所有注释、空行和无效规则，然后排序并去除重复项
          grep -v -E '^!|#|\[Adblock Plus' temp_list.txt | sed '/^$/d' | sort -u > final-rules.txt
          echo "规则处理完成！"
          
      # 第四步：把生成好的最终文件提交回你的仓库
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add final-rules.txt
          # 下面的提交信息可以自定义
          git commit -m "自动更新AdGuard规则" -a || echo "没有内容更新"
          git push
